Trantype.create!(id: 1, description: 'Débito', deb_or_decred: 'Entrada', signal: '+')
Trantype.create!(id: 2, description: 'Boleto', deb_or_decred: 'Saída', signal: '-')
Trantype.create!(id: 3, description: 'Financiamento', deb_or_decred: 'Saída', signal: '-')
Trantype.create!(id: 4, description: 'Crédito', deb_or_decred: 'Entrada', signal: '+')
Trantype.create!(id: 5, description: 'Recebimento Empréstimo', deb_or_decred: 'Entrada', signal: '+')
Trantype.create!(id: 6, description: 'Vendas', deb_or_decred: 'Entrada', signal: '+')
Trantype.create!(id: 7, description: 'Recebimento TED', deb_or_decred: 'Entrada', signal: '+')
Trantype.create!(id: 8, description: 'Recebimento DOC', deb_or_decred: 'Entrada', signal: '+')
Trantype.create!(id: 9, description: 'Aluguel', deb_or_decred: 'Saída', signal: '-')
